### ISSUE TITLE
DownloadFiles and UploadFiles conflict with RabbitMQTask

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.SFTP#212]
- Frends.Community.RabbitMQ.RabbitMQTask.ReadMessageString 1.6.3
- Frends.SFTP.DownloadFiles.SFTP.DownloadFiles 2.10.0 or Frends.SFTP.DownloadFiles.SFTP.DownloadFiles 2.10.0
- Using the RabbitMQ task and any of DownloadFiles/UploadFiles produces the following error:

```
System.IO.IOException
Message
connection.start was never received, likely due to a network timeout
StackTraceString
at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
at RabbitMQ.Client.Framing.Impl.Connection..ctor(IConnectionFactory factory, Boolean insist, IFrameHandler frameHandler, String clientProvidedName)
at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
InnerException
null
```

Internal issue link: FRR-203

**Comment by jefim** [comment]
We have tested this in very different setups and could not reproduce the problem. Until further additional input we are closing this issue.
